In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('ventas_videojuegos.csv')

In [9]:
df.head(1)

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011.0,Bethesda,7.12,6.35,6.99,2.26,22.72

In [7]:
df.tail(1)

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
203,Call of Duty: Modern Warfare 2,X360,Disparos,2009.0,Activision,5.15,3.59,0.41,1.0,10.15

In [10]:
df.shape

(204, 10)

In [13]:
df.columns

Index(['nombre', 'plataforma', 'genero', 'anio', 'editora', 'ventas_na',
       'ventas_eu', 'ventas_jp', 'ventas_otros', 'ventas_global'],
      dtype='str')

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nombre         204 non-null    str
 1   plataforma     204 non-null    str
 2   genero         204 non-null    str
 3   anio           197 non-null    float64
 4   editora        199 non-null    str
 5   ventas_na      204 non-null    float64
 6   ventas_eu      204 non-null    float64
 7   ventas_jp      204 non-null    float64
 8   ventas_otros   204 non-null    float64
 9   ventas_global  204 non-null    float64
dtypes: float64(6), str(4)
memory usage: 23.0 KB

In [16]:
df.dtypes

nombre               str
plataforma           str
genero               str
anio             float64
editora              str
ventas_na        float64
ventas_eu        float64
ventas_jp        float64
ventas_otros     float64
ventas_global    float64
dtype: object

In [17]:
df.describe()

,anio,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
count,197.000000,204.000000,204.000000,204.000000,204.000000,204.000000
mean,2011.959391,3.230441,2.640833,1.513676,0.773824,8.158775
std,8.460495,2.761133,2.404268,1.749858,0.747262,7.132819
min,1985.000000,0.210000,0.150000,0.020000,0.030000,0.450000
25%,2007.000000,1.415000,1.157500,0.360000,0.317500,3.545000
50%,2015.000000,2.325000,1.855000,0.905000,0.545000,5.970000
75%,2018.000000,4.097500,3.110000,2.140000,0.957500,9.947500
max,2023.000000,14.590000,12.770000,8.380000,3.710000,31.450000

In [20]:
df.duplicated().sum()

np.int64(4)

In [23]:
df = df.drop_duplicates()

In [24]:
df.shape

(200, 10)

In [26]:
df.isnull().sum()

nombre           0
plataforma       0
genero           0
anio             7
editora          5
ventas_na        0
ventas_eu        0
ventas_jp        0
ventas_otros     0
ventas_global    0
dtype: int64

In [27]:
df['editora'] = df['editora'].fillna('Desconocida')

In [28]:
df.isnull().sum()

nombre           0
plataforma       0
genero           0
anio             7
editora          0
ventas_na        0
ventas_eu        0
ventas_jp        0
ventas_otros     0
ventas_global    0
dtype: int64

In [30]:
df = df.dropna(subset=['anio'])

In [31]:
df.info()

<class 'pandas.DataFrame'>
Index: 193 entries, 0 to 203
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nombre         193 non-null    str
 1   plataforma     193 non-null    str
 2   genero         193 non-null    str
 3   anio           193 non-null    float64
 4   editora        193 non-null    str
 5   ventas_na      193 non-null    float64
 6   ventas_eu      193 non-null    float64
 7   ventas_jp      193 non-null    float64
 8   ventas_otros   193 non-null    float64
 9   ventas_global  193 non-null    float64
dtypes: float64(6), str(4)
memory usage: 23.3 KB

In [32]:
df['anio']

0      2011.0
1      2018.0
2      2020.0
3      2017.0
4      2021.0
        ...
199    2022.0
200    2017.0
201    2013.0
202    2009.0
203    2009.0
Name: anio, Length: 193, dtype: float64

In [33]:
df['anio'] = df['anio'].astype(int)

In [34]:
df.head()

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011,Bethesda,7.12,6.35,6.99,2.26,22.72
1,Assassin's Creed Odyssey,PS4,Accion,2018,Ubisoft,3.85,2.99,0.64,0.55,8.03
2,Fall Guys,PS4,Plataformas,2020,Devolver Digital,0.40,0.26,0.15,0.08,0.89
3,Tekken 7,PS4,Lucha,2017,Bandai Namco,1.09,0.90,1.10,0.33,3.42
4,It Takes Two,PS4,Aventura,2021,Electronic Arts,1.11,0.84,0.30,0.20,2.45

In [35]:
df

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011,Bethesda,7.12,6.35,6.99,2.26,22.72
1,Assassin's Creed Odyssey,PS4,Accion,2018,Ubisoft,3.85,2.99,0.64,0.55,8.03
2,Fall Guys,PS4,Plataformas,2020,Devolver Digital,0.40,0.26,0.15,0.08,0.89
3,Tekken 7,PS4,Lucha,2017,Bandai Namco,1.09,0.90,1.10,0.33,3.42
4,It Takes Two,PS4,Aventura,2021,Electronic Arts,1.11,0.84,0.30,0.20,2.45
...,...,...,...,...,...,...,...,...,...,...
199,Elden Ring,PS5,Rol,2022,Bandai Namco,2.25,1.82,2.81,0.61,7.49
200,Gran Turismo Sport,PS4,Carreras,2017,Desconocida,0.33,0.32,0.06,0.05,0.76
201,The Last of Us,PS3,Aventura,2013,Sony,3.09,2.00,0.87,0.41,6.37
202,Assassin's Creed II,X360,Accion,2009,Ubisoft,3.92,2.72,1.24,0.70,8.58
203,Call of Duty: Modern Warfare 2,X360,Disparos,2009,Activision,5.15,3.59,0.41,1.00,10.15

In [36]:
df = df.reset_index(drop=True)

In [37]:
df

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011,Bethesda,7.12,6.35,6.99,2.26,22.72
1,Assassin's Creed Odyssey,PS4,Accion,2018,Ubisoft,3.85,2.99,0.64,0.55,8.03
2,Fall Guys,PS4,Plataformas,2020,Devolver Digital,0.40,0.26,0.15,0.08,0.89
3,Tekken 7,PS4,Lucha,2017,Bandai Namco,1.09,0.90,1.10,0.33,3.42
4,It Takes Two,PS4,Aventura,2021,Electronic Arts,1.11,0.84,0.30,0.20,2.45
...,...,...,...,...,...,...,...,...,...,...
188,Elden Ring,PS5,Rol,2022,Bandai Namco,2.25,1.82,2.81,0.61,7.49
189,Gran Turismo Sport,PS4,Carreras,2017,Desconocida,0.33,0.32,0.06,0.05,0.76
190,The Last of Us,PS3,Aventura,2013,Sony,3.09,2.00,0.87,0.41,6.37
191,Assassin's Creed II,X360,Accion,2009,Ubisoft,3.92,2.72,1.24,0.70,8.58
192,Call of Duty: Modern Warfare 2,X360,Disparos,2009,Activision,5.15,3.59,0.41,1.00,10.15

In [38]:
df['nombre']

0         The Elder Scrolls V: Skyrim
1            Assassin's Creed Odyssey
2                           Fall Guys
3                            Tekken 7
4                        It Takes Two
                    ...
188                        Elden Ring
189                Gran Turismo Sport
190                    The Last of Us
191               Assassin's Creed II
192    Call of Duty: Modern Warfare 2
Name: nombre, Length: 193, dtype: str

In [41]:
df[['nombre','genero','ventas_global']]

                             nombre       genero  ventas_global
0       The Elder Scrolls V: Skyrim          Rol          22.72
1          Assassin's Creed Odyssey       Accion           8.03
2                         Fall Guys  Plataformas           0.89
3                          Tekken 7        Lucha           3.42
4                      It Takes Two     Aventura           2.45
..                              ...          ...            ...
188                      Elden Ring          Rol           7.49
189              Gran Turismo Sport     Carreras           0.76
190                  The Last of Us     Aventura           6.37
191             Assassin's Creed II       Accion           8.58
192  Call of Duty: Modern Warfare 2     Disparos          10.15

[193 rows x 3 columns]

In [44]:
df['genero'] == 'Rol'

0       True
1      False
2      False
3      False
4      False
       ...
188     True
189    False
190    False
191    False
192    False
Name: genero, Length: 193, dtype: bool

In [45]:
df[df['genero'] == 'Rol']

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011,Bethesda,7.12,6.35,6.99,2.26,22.72
10,Kingdom Hearts III,PS4,Rol,2019,Square Enix,1.23,1.02,1.36,0.30,3.91
12,Monster Hunter Rise,Switch,Rol,2021,Capcom,1.67,1.50,2.08,0.44,5.69
14,Pokemon Sword/Shield,Switch,Rol,2019,Nintendo,1.42,1.42,2.30,0.43,5.57
15,Pokemon Diamond/Pearl,DS,Rol,2006,Nintendo,6.08,4.99,7.40,1.99,20.46
20,Starfield,XOne,Rol,2023,Bethesda,0.49,0.39,0.48,0.13,1.49
21,Pokemon Scarlet/Violet,Switch,Rol,2022,Nintendo,2.36,2.17,3.36,0.68,8.57
26,Final Fantasy VII,PS1,Rol,1997,Square Enix,2.78,2.77,3.19,1.26,10.00
27,Diablo IV,PC,Rol,2023,Activision,0.75,0.55,0.54,0.25,2.09
31,Hades,Switch,Rol,2020,Supergiant Games,1.16,0.96,0.94,0.29,3.35
33,Pokemon Gold/Silver,GB,Rol,1999,Nintendo,5.39,3.99,6.73,1.35,17.46
35,Pokemon Red/Blue,GB,Rol,1996,Nintendo,6.94,6.02,8.38,2.31,23.65
40,Cyberpunk 2077,PC,Rol,2020,CD Projekt,2.57,1.75,2.14,0.64,7.10
42,Baldur's Gate 3,PS5,Rol,2023,Larian Studios,1.80,1.30,1.79,0.58,5.47
45,Baldur's Gate 3,PC,Rol,2023,Larian Studios,1.86,1.56,1.60,0.71,5.73
72,Chrono Trigger,SNES,Rol,1995,Square Enix,1.38,1.04,1.66,0.32,4.40
78,Diablo III,PC,Rol,2012,Activision,3.77,3.26,3.49,0.91,11.43
81,Final Fantasy X,PS2,Rol,2001,Square Enix,1.40,1.20,1.76,0.36,4.72
82,Fallout 4,PS4,Rol,2015,Bethesda,3.11,2.58,3.18,1.32,10.19
83,Dragon Quest XI,PS4,Rol,2017,Square Enix,1.28,1.15,1.56,0.58,4.57
84,Kingdom Hearts,PS2,Rol,2002,Square Enix,2.32,1.80,2.39,0.76,7.27
90,Xenoblade Chronicles 3,Switch,Rol,2022,Nintendo,1.01,0.78,1.25,0.37,3.41
93,Bloodborne,PS4,Rol,2015,Sony,1.28,0.98,1.20,0.41,3.87
96,Demon's Souls,PS5,Rol,2020,Sony,1.17,1.00,1.06,0.46,3.69
97,Fallout 3,X360,Rol,2008,Bethesda,3.47,2.78,3.41,0.91,10.57
102,The Witcher 3: Wild Hunt,PS4,Rol,2015,CD Projekt,3.30,2.26,3.03,0.87,9.46
103,Persona 5,PS4,Rol,2016,Sega,1.96,1.99,2.75,0.72,7.42
105,Final Fantasy XV,PS4,Rol,2016,Square Enix,0.70,0.63,0.85,0.18,2.36
106,The Witcher 3: Wild Hunt,PC,Rol,2015,CD Projekt,2.08,1.76,1.92,0.42,6.18
112,Dark Souls III,PS4,Rol,2016,Bandai Namco,0.30,0.30,0.40,0.09,1.09
118,World of Warcraft,PC,Rol,2004,Activision,2.93,2.52,2.62,0.79,8.86
135,The Elder Scrolls V: Skyrim,PS3,Rol,2011,Bethesda,11.14,6.68,8.29,2.91,29.02
139,Horizon Zero Dawn,PS4,Rol,2017,Sony,3.00,2.31,2.66,1.09,9.06
141,Pokemon Sun/Moon,3DS,Rol,2016,Nintendo,1.63,1.32,2.10,0.56,5.61
148,Hogwarts Legacy,PS5,Rol,2023,Warner Bros.,1.94,1.50,1.47,0.66,5.57
169,Monster Hunter: World,PS4,Rol,2018,Capcom,2.13,2.22,3.06,0.85,8.26
188,Elden Ring,PS5,Rol,2022,Bandai Namco,2.25,1.82,2.81,0.61,7.49

In [46]:
df[df['ventas_global']> 25]

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
17,Wii Fit,Wii,Deportes,2007,Nintendo,9.70,12.77,3.39,3.43,29.29
46,Grand Theft Auto V,PC,Accion,2015,Rockstar Games,13.76,9.55,3.54,2.86,29.71
76,New Super Mario Bros. Wii,Wii,Plataformas,2009,Nintendo,10.82,9.26,6.41,3.10,29.59
85,Minecraft,Switch,Aventura,2018,Mojang,13.01,7.67,3.57,1.47,25.72
95,Mario Kart 8 Deluxe,Switch,Carreras,2017,Nintendo,10.72,12.26,3.94,3.71,30.63
116,Wii Play,Wii,Puzzle,2006,Nintendo,8.73,7.55,7.69,1.18,25.15
120,The Legend of Zelda: Breath of the Wild,Switch,Aventura,2017,Nintendo,9.62,8.35,4.71,3.07,25.75
124,Mario Kart DS,DS,Carreras,2005,Nintendo,8.88,11.47,4.66,3.01,28.02
126,New Super Mario Bros.,DS,Plataformas,2006,Nintendo,9.37,8.30,5.27,3.01,25.95
135,The Elder Scrolls V: Skyrim,PS3,Rol,2011,Bethesda,11.14,6.68,8.29,2.91,29.02

In [47]:
df[(df['ventas_global']> 25) & (df['genero'] == 'Rol')]

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
135,The Elder Scrolls V: Skyrim,PS3,Rol,2011,Bethesda,11.14,6.68,8.29,2.91,29.02

In [50]:
jeugos_de_rol_o_post_2020 = df[(df['ventas_global']> 25)| (df['genero'] == 'Rol')]

In [51]:
jeugos_de_rol_o_post_2020

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011,Bethesda,7.12,6.35,6.99,2.26,22.72
10,Kingdom Hearts III,PS4,Rol,2019,Square Enix,1.23,1.02,1.36,0.30,3.91
12,Monster Hunter Rise,Switch,Rol,2021,Capcom,1.67,1.50,2.08,0.44,5.69
14,Pokemon Sword/Shield,Switch,Rol,2019,Nintendo,1.42,1.42,2.30,0.43,5.57
15,Pokemon Diamond/Pearl,DS,Rol,2006,Nintendo,6.08,4.99,7.40,1.99,20.46
17,Wii Fit,Wii,Deportes,2007,Nintendo,9.70,12.77,3.39,3.43,29.29
20,Starfield,XOne,Rol,2023,Bethesda,0.49,0.39,0.48,0.13,1.49
21,Pokemon Scarlet/Violet,Switch,Rol,2022,Nintendo,2.36,2.17,3.36,0.68,8.57
26,Final Fantasy VII,PS1,Rol,1997,Square Enix,2.78,2.77,3.19,1.26,10.00
27,Diablo IV,PC,Rol,2023,Activision,0.75,0.55,0.54,0.25,2.09
31,Hades,Switch,Rol,2020,Supergiant Games,1.16,0.96,0.94,0.29,3.35
33,Pokemon Gold/Silver,GB,Rol,1999,Nintendo,5.39,3.99,6.73,1.35,17.46
35,Pokemon Red/Blue,GB,Rol,1996,Nintendo,6.94,6.02,8.38,2.31,23.65
40,Cyberpunk 2077,PC,Rol,2020,CD Projekt,2.57,1.75,2.14,0.64,7.10
42,Baldur's Gate 3,PS5,Rol,2023,Larian Studios,1.80,1.30,1.79,0.58,5.47
45,Baldur's Gate 3,PC,Rol,2023,Larian Studios,1.86,1.56,1.60,0.71,5.73
46,Grand Theft Auto V,PC,Accion,2015,Rockstar Games,13.76,9.55,3.54,2.86,29.71
72,Chrono Trigger,SNES,Rol,1995,Square Enix,1.38,1.04,1.66,0.32,4.40
76,New Super Mario Bros. Wii,Wii,Plataformas,2009,Nintendo,10.82,9.26,6.41,3.10,29.59
78,Diablo III,PC,Rol,2012,Activision,3.77,3.26,3.49,0.91,11.43
81,Final Fantasy X,PS2,Rol,2001,Square Enix,1.40,1.20,1.76,0.36,4.72
82,Fallout 4,PS4,Rol,2015,Bethesda,3.11,2.58,3.18,1.32,10.19
83,Dragon Quest XI,PS4,Rol,2017,Square Enix,1.28,1.15,1.56,0.58,4.57
84,Kingdom Hearts,PS2,Rol,2002,Square Enix,2.32,1.80,2.39,0.76,7.27
85,Minecraft,Switch,Aventura,2018,Mojang,13.01,7.67,3.57,1.47,25.72
90,Xenoblade Chronicles 3,Switch,Rol,2022,Nintendo,1.01,0.78,1.25,0.37,3.41
93,Bloodborne,PS4,Rol,2015,Sony,1.28,0.98,1.20,0.41,3.87
95,Mario Kart 8 Deluxe,Switch,Carreras,2017,Nintendo,10.72,12.26,3.94,3.71,30.63
96,Demon's Souls,PS5,Rol,2020,Sony,1.17,1.00,1.06,0.46,3.69
97,Fallout 3,X360,Rol,2008,Bethesda,3.47,2.78,3.41,0.91,10.57
102,The Witcher 3: Wild Hunt,PS4,Rol,2015,CD Projekt,3.30,2.26,3.03,0.87,9.46
103,Persona 5,PS4,Rol,2016,Sega,1.96,1.99,2.75,0.72,7.42
105,Final Fantasy XV,PS4,Rol,2016,Square Enix,0.70,0.63,0.85,0.18,2.36
106,The Witcher 3: Wild Hunt,PC,Rol,2015,CD Projekt,2.08,1.76,1.92,0.42,6.18
112,Dark Souls III,PS4,Rol,2016,Bandai Namco,0.30,0.30,0.40,0.09,1.09
116,Wii Play,Wii,Puzzle,2006,Nintendo,8.73,7.55,7.69,1.18,25.15
118,World of Warcraft,PC,Rol,2004,Activision,2.93,2.52,2.62,0.79,8.86
120,The Legend of Zelda: Breath of the Wild,Switch,Aventura,2017,Nintendo,9.62,8.35,4.71,3.07,25.75
124,Mario Kart DS,DS,Carreras,2005,Nintendo,8.88,11.47,4.66,3.01,28.02
126,New Super Mario Bros.,DS,Plataformas,2006,Nintendo,9.37,8.30,5.27,3.01,25.95
135,The Elder Scrolls V: Skyrim,PS3,Rol,2011,Bethesda,11.14,6.68,8.29,2.91,29.02
139,Horizon Zero Dawn,PS4,Rol,2017,Sony,3.00,2.31,2.66,1.09,9.06
141,Pokemon Sun/Moon,3DS,Rol,2016,Nintendo,1.63,1.32,2.10,0.56,5.61
148,Hogwarts Legacy,PS5,Rol,2023,Warner Bros.,1.94,1.50,1.47,0.66,5.57
169,Monster Hunter: World,PS4,Rol,2018,Capcom,2.13,2.22,3.06,0.85,8.26
188,Elden Ring,PS5,Rol,2022,Bandai Namco,2.25,1.82,2.81,0.61,7.49

In [55]:
top10_ventas = df.sort_values('ventas_global', ascending=False).head(10)

In [56]:
top10_ventas

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
95,Mario Kart 8 Deluxe,Switch,Carreras,2017,Nintendo,10.72,12.26,3.94,3.71,30.63
46,Grand Theft Auto V,PC,Accion,2015,Rockstar Games,13.76,9.55,3.54,2.86,29.71
76,New Super Mario Bros. Wii,Wii,Plataformas,2009,Nintendo,10.82,9.26,6.41,3.10,29.59
17,Wii Fit,Wii,Deportes,2007,Nintendo,9.70,12.77,3.39,3.43,29.29
135,The Elder Scrolls V: Skyrim,PS3,Rol,2011,Bethesda,11.14,6.68,8.29,2.91,29.02
124,Mario Kart DS,DS,Carreras,2005,Nintendo,8.88,11.47,4.66,3.01,28.02
126,New Super Mario Bros.,DS,Plataformas,2006,Nintendo,9.37,8.30,5.27,3.01,25.95
120,The Legend of Zelda: Breath of the Wild,Switch,Aventura,2017,Nintendo,9.62,8.35,4.71,3.07,25.75
85,Minecraft,Switch,Aventura,2018,Mojang,13.01,7.67,3.57,1.47,25.72
116,Wii Play,Wii,Puzzle,2006,Nintendo,8.73,7.55,7.69,1.18,25.15

In [57]:
top_5_rol = df[df['genero'] == 'Rol'].sort_values('ventas_global', ascending=False).head(5)

In [58]:
top_5_rol

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
135,The Elder Scrolls V: Skyrim,PS3,Rol,2011,Bethesda,11.14,6.68,8.29,2.91,29.02
35,Pokemon Red/Blue,GB,Rol,1996,Nintendo,6.94,6.02,8.38,2.31,23.65
0,The Elder Scrolls V: Skyrim,X360,Rol,2011,Bethesda,7.12,6.35,6.99,2.26,22.72
15,Pokemon Diamond/Pearl,DS,Rol,2006,Nintendo,6.08,4.99,7.40,1.99,20.46
33,Pokemon Gold/Silver,GB,Rol,1999,Nintendo,5.39,3.99,6.73,1.35,17.46

In [59]:
df

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011,Bethesda,7.12,6.35,6.99,2.26,22.72
1,Assassin's Creed Odyssey,PS4,Accion,2018,Ubisoft,3.85,2.99,0.64,0.55,8.03
2,Fall Guys,PS4,Plataformas,2020,Devolver Digital,0.40,0.26,0.15,0.08,0.89
3,Tekken 7,PS4,Lucha,2017,Bandai Namco,1.09,0.90,1.10,0.33,3.42
4,It Takes Two,PS4,Aventura,2021,Electronic Arts,1.11,0.84,0.30,0.20,2.45
...,...,...,...,...,...,...,...,...,...,...
188,Elden Ring,PS5,Rol,2022,Bandai Namco,2.25,1.82,2.81,0.61,7.49
189,Gran Turismo Sport,PS4,Carreras,2017,Desconocida,0.33,0.32,0.06,0.05,0.76
190,The Last of Us,PS3,Aventura,2013,Sony,3.09,2.00,0.87,0.41,6.37
191,Assassin's Creed II,X360,Accion,2009,Ubisoft,3.92,2.72,1.24,0.70,8.58
192,Call of Duty: Modern Warfare 2,X360,Disparos,2009,Activision,5.15,3.59,0.41,1.00,10.15

In [63]:
df.groupby('genero')['ventas_global'].sum().sort_values(ascending=False)

genero
Rol            307.76
Aventura       220.32
Plataformas    186.44
Accion         163.53
Disparos       158.75
Carreras       145.87
Deportes       135.83
Lucha           72.49
Puzzle          63.31
Simulacion      45.10
Estrategia      25.02
Musica          17.51
Name: ventas_global, dtype: float64

In [68]:
df.groupby('genero')['nombre'].count().sort_values(ascending=False)

genero
Rol            37
Disparos       27
Aventura       26
Plataformas    21
Accion         20
Deportes       17
Carreras       15
Lucha           9
Estrategia      8
Musica          5
Puzzle          4
Simulacion      4
Name: nombre, dtype: int64

In [72]:
df['porcentaje_na'] = (df['ventas_na'] / df['ventas_global']) * 100

In [73]:
df

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global,porcentaje_na
0,The Elder Scrolls V: Skyrim,X360,Rol,2011,Bethesda,7.12,6.35,6.99,2.26,22.72,31.338028
1,Assassin's Creed Odyssey,PS4,Accion,2018,Ubisoft,3.85,2.99,0.64,0.55,8.03,47.945205
2,Fall Guys,PS4,Plataformas,2020,Devolver Digital,0.40,0.26,0.15,0.08,0.89,44.943820
3,Tekken 7,PS4,Lucha,2017,Bandai Namco,1.09,0.90,1.10,0.33,3.42,31.871345
4,It Takes Two,PS4,Aventura,2021,Electronic Arts,1.11,0.84,0.30,0.20,2.45,45.306122
...,...,...,...,...,...,...,...,...,...,...,...
188,Elden Ring,PS5,Rol,2022,Bandai Namco,2.25,1.82,2.81,0.61,7.49,30.040053
189,Gran Turismo Sport,PS4,Carreras,2017,Desconocida,0.33,0.32,0.06,0.05,0.76,43.421053
190,The Last of Us,PS3,Aventura,2013,Sony,3.09,2.00,0.87,0.41,6.37,48.508634
191,Assassin's Creed II,X360,Accion,2009,Ubisoft,3.92,2.72,1.24,0.70,8.58,45.687646
192,Call of Duty: Modern Warfare 2,X360,Disparos,2009,Activision,5.15,3.59,0.41,1.00,10.15,50.738916

In [74]:
df.shape

(193, 11)

In [75]:
df.groupby('genero')['porcentaje_na'].mean().sort_values(ascending=False)

genero
Disparos       49.135632
Musica         48.897654
Accion         46.566767
Estrategia     45.288339
Simulacion     43.483410
Aventura       43.454802
Plataformas    40.832940
Deportes       40.054441
Carreras       37.986649
Lucha          36.157824
Puzzle         34.562993
Rol            31.242472
Name: porcentaje_na, dtype: float64

In [77]:
df.groupby('plataforma')['nombre'].count()

plataforma
3DS           2
DS            5
Dreamcast     1
GB            3
GameCube      4
Genesis       1
N64           4
NES           1
PC           18
PS1           8
PS2           8
PS3          13
PS4          51
PS5          11
SNES          5
Switch       24
Wii          11
Wii U         2
X360         15
XOne          4
Xbox          2
Name: nombre, dtype: int64

In [78]:
df['plataforma'].value_counts()

plataforma
PS4          51
Switch       24
PC           18
X360         15
PS3          13
Wii          11
PS5          11
PS1           8
PS2           8
SNES          5
DS            5
XOne          4
N64           4
GameCube      4
GB            3
Wii U         2
Xbox          2
3DS           2
NES           1
Dreamcast     1
Genesis       1
Name: count, dtype: int64

In [81]:
df['editora'].value_counts().head(2)

editora
Nintendo    48
Sony        23
Name: count, dtype: int64

In [83]:
top10_ventas

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
95,Mario Kart 8 Deluxe,Switch,Carreras,2017,Nintendo,10.72,12.26,3.94,3.71,30.63
46,Grand Theft Auto V,PC,Accion,2015,Rockstar Games,13.76,9.55,3.54,2.86,29.71
76,New Super Mario Bros. Wii,Wii,Plataformas,2009,Nintendo,10.82,9.26,6.41,3.10,29.59
17,Wii Fit,Wii,Deportes,2007,Nintendo,9.70,12.77,3.39,3.43,29.29
135,The Elder Scrolls V: Skyrim,PS3,Rol,2011,Bethesda,11.14,6.68,8.29,2.91,29.02
124,Mario Kart DS,DS,Carreras,2005,Nintendo,8.88,11.47,4.66,3.01,28.02
126,New Super Mario Bros.,DS,Plataformas,2006,Nintendo,9.37,8.30,5.27,3.01,25.95
120,The Legend of Zelda: Breath of the Wild,Switch,Aventura,2017,Nintendo,9.62,8.35,4.71,3.07,25.75
85,Minecraft,Switch,Aventura,2018,Mojang,13.01,7.67,3.57,1.47,25.72
116,Wii Play,Wii,Puzzle,2006,Nintendo,8.73,7.55,7.69,1.18,25.15